"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 1.10.8.

"""

''' THIS FILE IS COMMON FOR ALL ENV SETTING (DEV,PROD,STAGE)'''

# IMPORT OS AND MESSAGE MODULE OF DJANGO
import os
from django.contrib.messages import constants as messages


# DEFINE THE INBUILT CUSTOM APPS 
INSTALLED_APPS = [
    'polls.apps.PollsConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'crispy_forms',
    'rest_framework',
    'bootstrap_modal_forms',
    'django_toggle_switch_widget',
    'corsheaders'
]

''' DEFINE MIDDLEWARES FROM DJANGO AND CUSTOM MIDDLEWARES ''' 
MIDDLEWARE = [
 'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'polls.router_middlewares.LoginRequiredMiddleware',
    'polls.router_middlewares.RouterMiddleware',
    'polls.router_middlewares.PermissionRequiredMiddleware',
]

'''ROOT REGEX URL MATCHING'''
ROOT_URLCONF = 'mysite.urls'

'''SET DJANGO TEMPLATE RENDERING PATH SETTING'''
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# IMPORT BOOTSTRAP FOR DJANGO FORMS
CRISPY_TEMPLATE_PACK = 'bootstrap4'

# A LIGHTWEIGHTED DJANGO SERVER (CAN CHANGE TO GUNICORN ON PRODUCTION)
WSGI_APPLICATION = 'mysite.wsgi.application'

''' WE HAVE DEFINED MULTIPLE DATABASES SETTING
    == PGSQL==
        DATABASE_1,DATABASE_2,DB_DEFAULT
    == MYSQL==
        DATABASE_3,DATABASE_4,DATABASE_5
'''

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'db_default',
        'USER': 'postgres',
        'PASSWORD': 'ansh@123',
        'HOST': 'localhost',
        'PORT': '5432',
    },
    'database_1': {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'NAME': 'database_1',
            'USER': 'postgres',
            'PASSWORD': 'ansh@123',
            'HOST': 'localhost',
            'PORT': '5432',
    },
    'database_2': {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'NAME': 'database_2',
            'USER': 'postgres',
            'PASSWORD': 'ansh@123',
            'HOST': 'localhost',
            'PORT': '5432',
    },
    'database_3': {
            'ENGINE': 'django.db.backends.mysql', 
            'NAME': 'database_3',
            'USER': 'root',
            'PASSWORD': 'ansh@123',
            'HOST': 'localhost',   # Or an IP Address that your DB is hosted on
            'PORT': '3306',
    },
    'database_4': {
            'ENGINE': 'django.db.backends.mysql', 
            'NAME': 'database_4',
            'USER': 'root',
            'PASSWORD': 'ansh@123',
            'HOST': 'localhost',   # Or an IP Address that your DB is hosted on
            'PORT': '3306',
        },
    'database_5': {
            'ENGINE': 'django.db.backends.mysql', 
            'NAME': 'database_5',
            'USER': 'root',
            'PASSWORD': 'ansh@123',
            'HOST': 'localhost',   # Or an IP Address that your DB is hosted on
            'PORT': '3306',
        }

}

# USE FOR THE MAILING PURPOSE
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

# DEFINE THE MAIL ENV VARIABLES WITH CREDENTIALS
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'anshul.upadhyay7@gmail.com'
EMAIL_HOST_PASSWORD = 'anshul@2447'
EMAIL_PORT = 465
EMAIL_USE_TLS = False
EMAIL_USE_SSL = True

# SET THE DEFAULT MAIL IF SMTP NOT SET
DEFAULT_FROM_EMAIL = 'Systango <anshul.upadhyay7@gmail.com>'


# PASSWORD VALIDATION
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# DEFINE THE DATABASE ROUTER [REQUIRED IN MULTIPLE DB SYSTEM]
DATABASE_ROUTERS = ['polls.router_middlewares.DatabaseRouter']


# Internationalization[DEFINE LANGUAGE AND TIME ZONE SETTINGS]
LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)[SET FOLDER PATH]
STATIC_URL = '/static/'

# SET REQUIRED LOGEDIN RESPONSE 
LOGIN_URL  = '/polls/login/'

# ADD THE MESSAGING NOTIFICATION HERE 
MESSAGE_TAGS = {
    messages.DEBUG: 'alert-info',
    messages.INFO: 'alert-info',
    messages.SUCCESS: 'alert-success',
    messages.WARNING: 'alert-warning',
    messages.ERROR: 'alert-danger',
}

# UNRESTRICT THE DIRECT USE OF URL WITHOUT LOGIN
LOGIN_EXEMPT_URLS = (
    r'polls/activate(.*)$',
    r'polls/home(.*)$',
    r'polls/login(.*)$',
    r'polls/forget_password(.*)$',
    r'polls/reset_password/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/?$',
    r'polls/reset_password_confirm/?$',
    r'admin(.*)$',
)

# DEFINE DB SWITCHING PATH OVER HERE TO HANDLE IN MIDDLEWARE
DATABASE_SWITCHING = (
    r'polls/product/(?P<db_name>\w+)/?$',
)

# authentication process 
AUTHENTICATION_BACKENDS = ['django.contrib.auth.backends.AllowAllUsersModelBackend']

# SET CROS SETTING OVER HERE WHITE LIST HOST AND DOMIN TO ALLOW
CORS_ORIGIN_ALLOW_ALL = True
CORS_ORIGIN_WHITELIST = []

# SET PERMISSION ENV VARIABLE IN MULTIPLE USER USER TYPE 
USER_REQUEST_PERMISSION = ['signup','permission_table','edit_permission']


