# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-23 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_database',
            field=models.CharField(choices=[('database_1', 'database_1'), ('database_2', 'database_2'), ('database_3', 'database_3'), ('database_4', 'database_4'), ('database_5', 'database_5'), ('default', 'dafault')], max_length=40),
        ),
    ]
