# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-24 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20200824_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
